version: 2.1

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Ensure backend infrastructure exist
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name my-stack
      - run:
          name: generate inventory
          command: |
            aws cloudformation list-exports \
              --query "Exports[?Name=='Udacity-PublicIp'].Value" \
              --no-paginate --output inventory

  run_ansible:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["2f:f4:27:a9:a8:ef:29:18:bb:b6:a4:8c:66:c3:8f:2d"]
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible
      - run:
          name: Configure server
          command: |
            ansible-playbook -i inventory.txt playbook.yml
  
  failed_on_purpose:
    docker:
      - image: ubuntu
    steps:
      - run: return 1
        
workflows:
  my_workflow:
    jobs:
      - run_ansible
      - failed_on_purpose:
          requires: ['run_ansible']